<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 3 </p>

In [ ]:
#Group1:
#Bikash Giri (101575097)
#Chia-Wei Chang (101570243)
#Diparshan Bhattarai (101494737)
#Hsi-Teng Liu (101576074)
#Gavriel Kirichenko (101119609)
#Abdul-Rasaq Omisesan (101571156)
#Callum Arul (101585383)
#Friba Hussainyar (101591222)

In [4]:
import numpy as np
from numpy.linalg import inv
from numpy.linalg import det

In [6]:
#Question1
A = np.array([[5, 2, 3],
              [6, 1, 3],
              [2, 4, 1]])

In [14]:
B = A[:2,:2]

In [24]:
C = A[1:,1:]

In [26]:
print(A)
print(B)
print(C)

[[5 2 3]
 [6 1 3]
 [2 4 1]]
[[5 2]
 [6 1]]
[[1 3]
 [4 1]]


In [28]:
#Question2
D = np.array([[4, -7, 4],
              [5, 6, -1],
              [-4, 2, 5]])

In [30]:
print(D)

[[ 4 -7  4]
 [ 5  6 -1]
 [-4  2  5]]


In [40]:
#Question3
np.matmul(A, D)

array([[ 18, -17,  33],
       [ 17, -30,  38],
       [ 24,  12,   9]])

In [34]:
np.matmul(D, A)

array([[-14,  17,  -5],
       [ 59,  12,  32],
       [  2,  14,  -1]])

In [72]:
#Question4
# Manually calculate
# Determinant Calculation B = ad−bc
print( f"Determinant  {5*1 - 2*6}")

# Inverse Calculation
print( f"Inverse  {[1/-7],[-2/-7],[6/7], [5/-7] }" ) 

Determinant  -7
Inverse  ([-0.14285714285714285], [0.2857142857142857], [0.8571428571428571], [-0.7142857142857143])


In [74]:
#numpy to calculate
det_B = np.linalg.det(B)
print (det_B)
inv_B = np.linalg.inv(B)
print (inv_B)

-6.999999999999999
[[-0.14285714  0.28571429]
 [ 0.85714286 -0.71428571]]


In [78]:
#Question5
inv_D = np.linalg.inv(D)
print(inv_D)

[[ 0.07785888  0.10462287 -0.04136253]
 [-0.05109489  0.08759124  0.05839416]
 [ 0.08272506  0.0486618   0.14355231]]


In [80]:
print(np.matmul(D, inv_D))
print(np.matmul(inv_D, D))

[[ 1.00000000e+00  1.11022302e-16  0.00000000e+00]
 [ 1.38777878e-17  1.00000000e+00  0.00000000e+00]
 [ 5.55111512e-17 -8.32667268e-17  1.00000000e+00]]
[[ 1.00000000e+00  2.49800181e-16 -2.77555756e-17]
 [ 2.77555756e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
#𝐷𝐷^-1and 𝐷^-1𝐷 should be 
[1,0,0],[0,1,0],[0,0,1] and D is invertible.
#We did not get zero but the number very close to zero for the result.