<p style="font-family: Arial; font-size:3em;color:black;"> Lab Exercise 1 </p>

In [3]:
# importing numpy
import numpy as np

In [31]:
# Create a numpy array with the elements "1, 2, 3, 5, 0", print the array and test if all of its elements are non-zero.
newarray = np.array([1,2,3,5,0])
nonzero_indices = np.nonzero(newarray)
print("non-zero elements:", nonzero_indices)

all_nonzero = np.all(newarray != 0)
print("Are all elements non-zero?", all_nonzero)

non-zero elements: (array([0, 1, 2, 3], dtype=int64),)
Are all elements non-zero? False


In [43]:
# Create a numpy array with the elements "3, -1, 3, 7, 2", print the array and test if any of its elements is non-zero.

newarray1 = np.array([3,-1,3,7,2])

for i in np.nonzero(newarray1):
    print(newarray1[i])

[ 3 -1  3  7  2]


In [45]:
# Create a numpy array with the elements "0, 0, 0, 0", print the array and test if any of its elements is non-zero.

zero_array = np.array([0, 0, 0, 0, 0])
print(zero_array)

print(np.any(zero_array))

[0 0 0 0 0]
False


In [49]:
# Create a numpy array with the elements "56, -2, 7", print the array and the amount of memory required to store it.

array3 = np.array([56, -2, 7])
print(array3)

print(array3.nbytes)

[56 -2  7]
12


In [53]:
# Create a numpy array with 10 zeros and print the array.
zeros = np.zeros(10)
print(zeros)

# Create a numpy array with 6 ones and print the array.
ones = np.ones(6)
print(ones)

# Create a numpy array with 12 '3's and print the array. [3 3 3 3 3 3 3 3 3 3 3 3]
threes  = 3*np.ones(12)
print(threes)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1.]
[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


In [57]:
# Create a numpy array of the integers from 8 to 20 and print the array. (make sure 20 itself is included) hint:  use "arange" method
array_8_to_20 = np.arange(8, 21)
print(array_8_to_20)
# Create a numpy array of the even integers from 8 to 20 and print the array. (make sure 20 itself is included)   hint:  use "arange" method
even_array = np.arange(8, 21, 2)
print(even_array)

[ 8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 8 10 12 14 16 18 20]


In [63]:
def random_array_stats(size):
    array = np.random.normal(loc=2, scale=0.5, size=size)
    print(f"Array of size {size}:")
    print(f"Mean: {np.mean(array)}")
    print(f"Max: {np.max(array)}")
    print(f"Min: {np.min(array)}")
    print(f"Std: {np.std(array)}\n")

# Create a numpy array consisting of 100 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array_stats(100)
# Create a numpy array consisting of 1000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array_stats(1000)
# Create a numpy array consisting of 1000000 random elements from normal distribution with mean of 2 and std of 0.5. Print the mean, max, min and std of the array.
random_array_stats(1000000)

# (Bonus question) Looking at the three above examples with 1000, 5000, and 10000 random elements, do you have any observations about mean and std values?

#As the size of the random array increases, the computed mean and standard deviation get closer to the theoretical values (mean = 2, std = 0.5). 
#This is due to the Law of Large Numbers.


#NumPy 的 np.random.normal 函數來生成一個遵循正態分佈（Normal Distribution, 又稱高斯分佈）的隨機數組。
#np.random.normal(loc, scale, size)
#loc：分佈的均值（mean），即正態分佈的中心點。
#在這裡，loc=2 表示生成的數據的均值為 2。
#scale：分佈的標準差（standard deviation），即數據的擴散程度。
#在這裡，scale=0.5 表示數據的標準差為 0.5，這決定了數據的集中程度或波動範圍。
#size：生成數據的大小（數組的形狀）。
#在這裡，size=size 表示生成數組的元素數量由函數參數 size 確定，可以是單一數字（生成 1D 數組）或元組（生成多維數組）。


#大數法則（Law of Large Numbers, LLN） 是統計學的一條基本理論，它描述了隨著試驗次數（或樣本數量）的增加，隨機現象的平均結果會逐漸趨近於期望值（理論平均值）的現象。

Array of size 100:
Mean: 1.9659313623378403
Max: 2.7733521032249335
Min: 0.9766191923591758
Std: 0.41994474291417805

Array of size 1000:
Mean: 1.9776152257868478
Max: 3.890305016063797
Min: 0.26306204475141737
Std: 0.5217231009190669

Array of size 1000000:
Mean: 1.9999881290670989
Max: 4.506297803483649
Min: -0.3520505301255774
Std: 0.500747950793001

